transfer file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,22 +1,23 @@
 #!/usr/bin/env bash
-# Check if all 4 parameters are provided, else display usage
-if [ $# -lt 4 ]; then
+# Check if the number of parameters is correct
+if [ "$#" -lt 4 ]; then
     echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
     exit 1
 fi
 
-# Extract parameters
-path_to_file=$1
-ip=$2
+# Assign parameter values to variables
+file_path=$1
+server_ip=$2
 username=$3
 ssh_key=$4
 
-# Transfer file using scp
-scp -o StrictHostKeyChecking=no -i "$ssh_key" "$path_to_file" "$username@$ip:~/"
+# Transfer the file using scp
+scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip:~"
 
-# Check if scp command was successful
-if [ $? -eq 0 ]; then
-    echo "File transfer successful!"
+# Check if the file transfer was successful
+if [ "$?" -eq 0 ]; then
+    echo "File transferred successfully."
 else
-    echo "File transfer failed!"
+    echo "File transfer failed."
 fi
+
